#include "defines.h"
#include "defines_battle.h"
#include "../include/new/animated_trainer_pics.h"

/*
animated_trainer_pics.c
	2-frame animation for the opponent trainer sprite in battle.

	AUTOMATIC (recommended):
		Put the PNGs in graphics/animated_trainers/ and compile with a_makepy.bat.
		scripts/animated_trainers.py fills src/animated_trainer_pics_table.h by itself
		(recognizes the trainer, fixes the file name, the layout and the palette order).

	MANUAL (optional):
		Add lines below, before {0xFFFF...}:
		    {TRAINER_PIC_ID, <FILE_NAME>Tiles, FRAME_DURATION, PLAY_COUNT},
		and declare "extern const u32 <FILE_NAME>Tiles[];" above the table.

	Trainers that are not in the table keep working exactly like before.
*/

#include "animated_trainer_pics_table.h" //Generated by scripts/animated_trainers.py

static const struct AnimatedTrainerPic sAnimatedTrainerPics[] =
{
	ANIMATED_TRAINER_PICS_AUTO //Entries created from graphics/animated_trainers/*.png
	//{0x6A, MeuTreinadorTiles, 16, 0}, //Manual example: trainer sprite 0x6A, changes image every 16 frames, loops forever
	{0xFFFF, NULL, 0, 0}, //Keep this line at the end
};

#define TRAINER_PIC_FRAME_TILES ((64 * 64) / 64) //64 tiles of 8x8 per 64x64 frame
#define TRAINER_PIC_FRAME_SIZE (64 * 64 / 2)     //0x800 bytes per 4bpp 64x64 frame

static const struct AnimatedTrainerPic* GetAnimatedTrainerPic(u16 trainerPicId)
{
	u32 i;

	for (i = 0; sAnimatedTrainerPics[i].trainerPicId != 0xFFFF; ++i)
	{
		if (sAnimatedTrainerPics[i].trainerPicId == trainerPicId && sAnimatedTrainerPics[i].tiles != NULL)
			return &sAnimatedTrainerPics[i];
	}

	return NULL;
}

//Replaces DecompressTrainerFrontPic: animated trainers load both frames, the others use the vanilla function
void LoadTrainerFrontPicWithAnim(u16 trainerPicId, u8 battlerId)
{
	struct SpriteSheet sheet;
	u8 position;
	const struct AnimatedTrainerPic* anim = GetAnimatedTrainerPic(trainerPicId);

	if (anim == NULL || gMonSpritesGfxPtr == NULL)
	{
		DecompressTrainerFrontPic(trainerPicId, battlerId);
		return;
	}

	position = GetBattlerPosition(battlerId);
	LZ77UnCompWram(anim->tiles, gMonSpritesGfxPtr->sprites[position]); //Each buffer holds 0x2000 bytes, 2 frames use 0x1000
	sheet.data = gMonSpritesGfxPtr->sprites[position];
	sheet.size = TRAINER_PIC_FRAME_SIZE * 2;
	sheet.tag = gTrainerFrontPicTable[trainerPicId].tag;
	FreeSpriteTilesByTag(sheet.tag); //Make sure the tag points to this 2-frame sheet, not an older 1-frame copy
	LoadSpriteSheet(&sheet);
	LoadCompressedSpritePaletteUsingHeap(&gTrainerFrontPicPaletteTable[trainerPicId]);
}

#define tSpriteId    data[0]
#define tTileStart   data[1]
#define tDuration    data[2]
#define tTimer       data[3]
#define tFrame       data[4]
#define tPicId       data[5]
#define tPlaysLeft   data[6]

static void Task_AnimateTrainerPic(u8 taskId)
{
	struct Sprite* sprite = &gSprites[gTasks[taskId].tSpriteId];

	//Stop when the trainer sprite is gone or its slot was reused by another sprite
	if (!sprite->inUse || sprite->oam.affineParam != (u16) gTasks[taskId].tPicId)
	{
		DestroyTask(taskId);
		return;
	}

	if (++gTasks[taskId].tTimer < gTasks[taskId].tDuration)
		return;

	gTasks[taskId].tTimer = 0;
	gTasks[taskId].tFrame ^= 1;
	sprite->oam.tileNum = gTasks[taskId].tTileStart + (gTasks[taskId].tFrame ? TRAINER_PIC_FRAME_TILES : 0);

	if (gTasks[taskId].tFrame == 0 && gTasks[taskId].tPlaysLeft != 0)
	{
		if (--gTasks[taskId].tPlaysLeft == 0)
			DestroyTask(taskId); //Finished, stays on frame 1
	}
}

//Call after the trainer sprite was created and its oam.tileNum/affineParam were set
void TryStartTrainerPicAnim(u8 spriteId, u16 trainerPicId)
{
	u8 taskId;
	u16 tileStart;
	const struct AnimatedTrainerPic* anim = GetAnimatedTrainerPic(trainerPicId);

	if (anim == NULL || spriteId >= MAX_SPRITES)
		return;

	tileStart = GetSpriteTileStartByTag(gTrainerFrontPicTable[trainerPicId].tag);
	if (tileStart == 0xFFFF)
		return;

	taskId = CreateTask(Task_AnimateTrainerPic, 0x50);
	if (taskId >= NUM_TASKS)
		return;

	gSprites[spriteId].oam.tileNum = tileStart;
	gTasks[taskId].tSpriteId = spriteId;
	gTasks[taskId].tTileStart = tileStart;
	gTasks[taskId].tDuration = (anim->frameDuration == 0) ? 1 : anim->frameDuration;
	gTasks[taskId].tTimer = 0;
	gTasks[taskId].tFrame = 0;
	gTasks[taskId].tPicId = trainerPicId;
	gTasks[taskId].tPlaysLeft = anim->playCount;
}
