#pragma once

#include "../../src/defines.h"
#include "../../include/constants/species.h"

// ============================================================================
//  POOL DE ESPECIES - RANDOM TRAINER TEAM (CFRU-expansion)
// ----------------------------------------------------------------------------
//  Usado por FLAG_RANDOM_TRAINER_TEAM (include/constants/flags.h, = 0x3E3).
//
//  Quando essa flag esta ativa, TryReplaceNormalTrainerSpecies (src/build_pokemon.c)
//  sorteia, para cada Pokemon de cada treinador NPC (lado B_SIDE_OPPONENT), uma
//  especie aleatoria e SEM REPETICAO dentro do mesmo time a partir deste array.
//  Nivel, item segurado e moves originalmente definidos para aquele treinador NAO
//  sao alterados - so a especie muda.
//
//  Esta lista foi extraida das especies unicas que aparecem em
//  include/new/random_trainer_pool_full.h (o pool "completo" usado por
//  FLAG_RANDOM_TRAINER_POOL / FLAG_RANDOM_GIVEMON_POOL), mas os dois arrays sao
//  independentes: pode editar, adicionar ou remover especies aqui sem afetar o outro.
//
//  Regra seguida ao montar esta lista: apenas Pokemon de ultimo estagio de evolucao
//  ou estagio unico (a mesma regra do pool completo).
//
//  Total: 476 especies.
//
//  Para adicionar/remover pokemon, edite direto este arquivo, so precisa do nome
//  SPECIES_X separado por virgula - nao tem moves/item/nature aqui.
// ============================================================================

const u16 gRandomTrainerSpeciesPool[] =
{
	SPECIES_VENUSAUR, SPECIES_CHARIZARD, SPECIES_BLASTOISE, SPECIES_BUTTERFREE,
	SPECIES_BEEDRILL, SPECIES_PIDGEOT, SPECIES_RATICATE, SPECIES_FEAROW,
	SPECIES_ARBOK, SPECIES_RAICHU, SPECIES_SANDSLASH, SPECIES_NIDOKING,
	SPECIES_NIDOQUEEN, SPECIES_CLEFABLE, SPECIES_NINETALES, SPECIES_WIGGLYTUFF,
	SPECIES_VILEPLUME, SPECIES_PARASECT, SPECIES_VENOMOTH, SPECIES_DUGTRIO,
	SPECIES_PERSIAN, SPECIES_GOLDUCK, SPECIES_PRIMEAPE, SPECIES_ARCANINE,
	SPECIES_POLIWRATH, SPECIES_ALAKAZAM, SPECIES_MACHAMP, SPECIES_VICTREEBEL,
	SPECIES_TENTACRUEL, SPECIES_GOLEM, SPECIES_RAPIDASH, SPECIES_SLOWBRO,
	SPECIES_MAGNETON, SPECIES_FARFETCHD, SPECIES_DODRIO, SPECIES_DEWGONG,
	SPECIES_MUK, SPECIES_CLOYSTER, SPECIES_GENGAR, SPECIES_ONIX,
	SPECIES_HYPNO, SPECIES_KINGLER, SPECIES_ELECTRODE, SPECIES_EXEGGUTOR,
	SPECIES_MAROWAK, SPECIES_HITMONLEE, SPECIES_HITMONCHAN, SPECIES_LICKITUNG,
	SPECIES_WEEZING, SPECIES_RHYDON, SPECIES_CHANSEY, SPECIES_KANGASKHAN,
	SPECIES_SEAKING, SPECIES_STARMIE, SPECIES_MR_MIME, SPECIES_JYNX,
	SPECIES_ELECTABUZZ, SPECIES_MAGMAR, SPECIES_PINSIR, SPECIES_TAUROS,
	SPECIES_GYARADOS, SPECIES_LAPRAS, SPECIES_VAPOREON, SPECIES_JOLTEON,
	SPECIES_FLAREON, SPECIES_OMASTAR, SPECIES_KABUTOPS, SPECIES_AERODACTYL,
	SPECIES_SNORLAX, SPECIES_ARTICUNO, SPECIES_ZAPDOS, SPECIES_MOLTRES,
	SPECIES_DRAGONITE, SPECIES_MEWTWO, SPECIES_MEW, SPECIES_MEGANIUM,
	SPECIES_TYPHLOSION, SPECIES_FERALIGATR, SPECIES_FURRET, SPECIES_NOCTOWL,
	SPECIES_LEDIAN, SPECIES_ARIADOS, SPECIES_CROBAT, SPECIES_LANTURN,
	SPECIES_XATU, SPECIES_AMPHAROS, SPECIES_BELLOSSOM, SPECIES_AZUMARILL,
	SPECIES_SUDOWOODO, SPECIES_POLITOED, SPECIES_JUMPLUFF, SPECIES_SUNFLORA,
	SPECIES_QUAGSIRE, SPECIES_ESPEON, SPECIES_UMBREON, SPECIES_SLOWKING,
	SPECIES_MISDREAVUS, SPECIES_GIRAFARIG, SPECIES_FORRETRESS, SPECIES_DUNSPARCE,
	SPECIES_GLIGAR, SPECIES_STEELIX, SPECIES_GRANBULL, SPECIES_QWILFISH,
	SPECIES_SCIZOR, SPECIES_SHUCKLE, SPECIES_HERACROSS, SPECIES_URSARING,
	SPECIES_MAGCARGO, SPECIES_CORSOLA, SPECIES_OCTILLERY, SPECIES_DELIBIRD,
	SPECIES_MANTINE, SPECIES_SKARMORY, SPECIES_HOUNDOOM, SPECIES_KINGDRA,
	SPECIES_DONPHAN, SPECIES_PORYGON2, SPECIES_STANTLER, SPECIES_SMEARGLE,
	SPECIES_HITMONTOP, SPECIES_MILTANK, SPECIES_RAIKOU, SPECIES_ENTEI,
	SPECIES_SUICUNE, SPECIES_TYRANITAR, SPECIES_LUGIA, SPECIES_HO_OH,
	SPECIES_CELEBI, SPECIES_SCEPTILE, SPECIES_BLAZIKEN, SPECIES_SWAMPERT,
	SPECIES_MIGHTYENA, SPECIES_LINOONE, SPECIES_BEAUTIFLY, SPECIES_DUSTOX,
	SPECIES_LUDICOLO, SPECIES_SHIFTRY, SPECIES_SWELLOW, SPECIES_PELIPPER,
	SPECIES_MASQUERAIN, SPECIES_NINJASK, SPECIES_SHEDINJA, SPECIES_EXPLOUD,
	SPECIES_HARIYAMA, SPECIES_DELCATTY, SPECIES_SABLEYE, SPECIES_MAWILE,
	SPECIES_AGGRON, SPECIES_MEDICHAM, SPECIES_MANECTRIC, SPECIES_PLUSLE,
	SPECIES_MINUN, SPECIES_VOLBEAT, SPECIES_ILLUMISE, SPECIES_ROSELIA,
	SPECIES_SWALOT, SPECIES_SHARPEDO, SPECIES_WAILORD, SPECIES_CAMERUPT,
	SPECIES_TORKOAL, SPECIES_GRUMPIG, SPECIES_CACTURNE, SPECIES_ALTARIA,
	SPECIES_ZANGOOSE, SPECIES_SEVIPER, SPECIES_LUNATONE, SPECIES_SOLROCK,
	SPECIES_WHISCASH, SPECIES_CRAWDAUNT, SPECIES_MILOTIC, SPECIES_CASTFORM,
	SPECIES_KECLEON, SPECIES_BANETTE, SPECIES_DUSCLOPS, SPECIES_TROPIUS,
	SPECIES_CHIMECHO, SPECIES_ABSOL, SPECIES_GLALIE, SPECIES_WALREIN,
	SPECIES_HUNTAIL, SPECIES_GOREBYSS, SPECIES_RELICANTH, SPECIES_LUVDISC,
	SPECIES_SALAMENCE, SPECIES_METAGROSS, SPECIES_REGIROCK, SPECIES_REGICE,
	SPECIES_REGISTEEL, SPECIES_LATIAS, SPECIES_LATIOS, SPECIES_KYOGRE,
	SPECIES_GROUDON, SPECIES_RAYQUAZA, SPECIES_JIRACHI, SPECIES_DEOXYS,
	SPECIES_TORTERRA, SPECIES_INFERNAPE, SPECIES_EMPOLEON, SPECIES_STARAPTOR,
	SPECIES_BIBAREL, SPECIES_KRICKETUNE, SPECIES_LUXRAY, SPECIES_ROSERADE,
	SPECIES_MISMAGIUS, SPECIES_HONCHKROW, SPECIES_SKUNTANK, SPECIES_BRONZONG,
	SPECIES_CHATOT, SPECIES_SPIRITOMB, SPECIES_GARCHOMP, SPECIES_LUCARIO,
	SPECIES_HIPPOWDON, SPECIES_DRAPION, SPECIES_TOXICROAK, SPECIES_CARNIVINE,
	SPECIES_LUMINEON, SPECIES_ABOMASNOW, SPECIES_WEAVILE, SPECIES_MAGNEZONE,
	SPECIES_LICKILICKY, SPECIES_RHYPERIOR, SPECIES_TANGROWTH, SPECIES_ELECTIVIRE,
	SPECIES_MAGMORTAR, SPECIES_TOGEKISS, SPECIES_YANMEGA, SPECIES_LEAFEON,
	SPECIES_GLACEON, SPECIES_GLISCOR, SPECIES_MAMOSWINE, SPECIES_PORYGON_Z,
	SPECIES_GALLADE, SPECIES_PROBOPASS, SPECIES_DUSKNOIR, SPECIES_FROSLASS,
	SPECIES_ROTOM, SPECIES_UXIE, SPECIES_MESPRIT, SPECIES_AZELF,
	SPECIES_DIALGA, SPECIES_PALKIA, SPECIES_HEATRAN, SPECIES_GIRATINA,
	SPECIES_CRESSELIA, SPECIES_MANAPHY, SPECIES_DARKRAI, SPECIES_SHAYMIN,
	SPECIES_ARCEUS, SPECIES_SERPERIOR, SPECIES_EMBOAR, SPECIES_SAMUROTT,
	SPECIES_WATCHOG, SPECIES_STOUTLAND, SPECIES_SIMISAGE, SPECIES_SIMISEAR,
	SPECIES_SIMIPOUR, SPECIES_UNFEZANT, SPECIES_GIGALITH, SPECIES_SWOOBAT,
	SPECIES_EXCADRILL, SPECIES_AUDINO, SPECIES_CONKELDURR, SPECIES_SEISMITOAD,
	SPECIES_LEAVANNY, SPECIES_SCOLIPEDE, SPECIES_WHIMSICOTT, SPECIES_LILLIGANT,
	SPECIES_BASCULIN_RED, SPECIES_KROOKODILE, SPECIES_DARMANITAN, SPECIES_MARACTUS,
	SPECIES_CRUSTLE, SPECIES_SCRAFTY, SPECIES_SIGILYPH, SPECIES_COFAGRIGUS,
	SPECIES_CARRACOSTA, SPECIES_ARCHEOPS, SPECIES_GARBODOR, SPECIES_ZOROARK,
	SPECIES_GOTHITELLE, SPECIES_REUNICLUS, SPECIES_SWANNA, SPECIES_VANILLUXE,
	SPECIES_SAWSBUCK, SPECIES_EMOLGA, SPECIES_ESCAVALIER, SPECIES_AMOONGUSS,
	SPECIES_JELLICENT, SPECIES_ALOMOMOLA, SPECIES_GALVANTULA, SPECIES_FERROTHORN,
	SPECIES_KLINKLANG, SPECIES_EELEKTROSS, SPECIES_BEHEEYEM, SPECIES_CHANDELURE,
	SPECIES_HAXORUS, SPECIES_BEARTIC, SPECIES_CRYOGONAL, SPECIES_ACCELGOR,
	SPECIES_MIENSHAO, SPECIES_BOUFFALANT, SPECIES_BRAVIARY, SPECIES_MANDIBUZZ,
	SPECIES_HELIOLISK, SPECIES_TYRANTRUM, SPECIES_AURORUS, SPECIES_KLEFKI,
	SPECIES_VOLCARONA, SPECIES_COBALION, SPECIES_TERRAKION, SPECIES_VIRIZION,
	SPECIES_TORNADUS, SPECIES_THUNDURUS, SPECIES_LANDORUS, SPECIES_KYUREM,
	SPECIES_KELDEO, SPECIES_MELOETTA, SPECIES_GENESECT, SPECIES_CHESNAUGHT,
	SPECIES_DELPHOX, SPECIES_GRENINJA, SPECIES_DIGGERSBY, SPECIES_TALONFLAME,
	SPECIES_VIVILLON, SPECIES_PYROAR, SPECIES_FLORGES, SPECIES_GOGOAT,
	SPECIES_PANGORO, SPECIES_FURFROU, SPECIES_MEOWSTIC, SPECIES_AEGISLASH,
	SPECIES_MALAMAR, SPECIES_BARBARACLE, SPECIES_DRAGALGE, SPECIES_CLAWITZER,
	SPECIES_GOODRA, SPECIES_TREVENANT, SPECIES_GOURGEIST, SPECIES_AVALUGG,
	SPECIES_NOIVERN, SPECIES_XERNEAS, SPECIES_YVELTAL, SPECIES_ZYGARDE,
	SPECIES_DIANCIE, SPECIES_HOOPA, SPECIES_VOLCANION, SPECIES_DECIDUEYE,
	SPECIES_INCINEROAR, SPECIES_PRIMARINA, SPECIES_TOUCANNON, SPECIES_GUMSHOOS,
	SPECIES_VIKAVOLT, SPECIES_CRABOMINABLE, SPECIES_ORICORIO, SPECIES_RIBOMBEE,
	SPECIES_LYCANROC, SPECIES_TOXAPEX, SPECIES_MUDSDALE, SPECIES_ARAQUANID,
	SPECIES_LURANTIS, SPECIES_SHIINOTIC, SPECIES_SALAZZLE, SPECIES_BEWEAR,
	SPECIES_TSAREENA, SPECIES_COMFEY, SPECIES_ORANGURU, SPECIES_PASSIMIAN,
	SPECIES_PALOSSAND, SPECIES_PYUKUMUKU, SPECIES_MIMIKYU, SPECIES_BRUXISH,
	SPECIES_DRAMPA, SPECIES_TYPE_NULL, SPECIES_SILVALLY, SPECIES_MINIOR_RED,
	SPECIES_TOGEDEMARU, SPECIES_KOMMO_O, SPECIES_TAPU_KOKO, SPECIES_TAPU_LELE,
	SPECIES_TAPU_BULU, SPECIES_TAPU_FINI, SPECIES_SOLGALEO, SPECIES_LUNALA,
	SPECIES_NECROZMA, SPECIES_MAGEARNA, SPECIES_MARSHADOW, SPECIES_RILLABOOM,
	SPECIES_CINDERACE, SPECIES_INTELEON, SPECIES_CORVIKNIGHT, SPECIES_ORBEETLE,
	SPECIES_THIEVUL, SPECIES_ELDEGOSS, SPECIES_DUBWOOL, SPECIES_DREDNAW,
	SPECIES_BOLTUND, SPECIES_CENTISKORCH, SPECIES_GRIMMSNARL, SPECIES_ALCREMIE_STRAWBERRY,
	SPECIES_FALINKS, SPECIES_PINCURCHIN, SPECIES_FROSMOTH, SPECIES_STONJOURNER,
	SPECIES_EISCUE, SPECIES_INDEEDEE, SPECIES_MORPEKO, SPECIES_COPPERAJAH,
	SPECIES_DURALUDON, SPECIES_DRAGAPULT, SPECIES_ZACIAN, SPECIES_ZAMAZENTA,
	SPECIES_ETERNATUS, SPECIES_URSHIFU_SINGLE, SPECIES_REGIELEKI, SPECIES_REGIDRAGO,
	SPECIES_GLASTRIER, SPECIES_SPECTRIER, SPECIES_CALYREX, SPECIES_MEOWSCARADA,
	SPECIES_SKELEDIRGE, SPECIES_QUAQUAVAL, SPECIES_OINKOLOGNE, SPECIES_PAWMOT,
	SPECIES_DACHSBUN, SPECIES_ARBOLIVA, SPECIES_GARGANACL, SPECIES_ARMAROUGE,
	SPECIES_CERULEDGE, SPECIES_KILOWATTREL, SPECIES_MABOSSTIFF, SPECIES_GRAFAIAI,
	SPECIES_BRAMBLEGHAST, SPECIES_TOEDSCRUEL, SPECIES_KLAWF, SPECIES_ORTHWORM,
	SPECIES_CYCLIZAR, SPECIES_REVAVROOM, SPECIES_ESPATHRA, SPECIES_TINKATON,
	SPECIES_WUGTRIO, SPECIES_BOMBIRDIER, SPECIES_FLAMIGO, SPECIES_VELUZA,
	SPECIES_DONDOZO, SPECIES_ANNIHILAPE, SPECIES_CLODSIRE, SPECIES_FARIGIRAF,
	SPECIES_DUDUNSPARCE, SPECIES_KINGAMBIT, SPECIES_GREAT_TUSK, SPECIES_IRON_TREADS,
	SPECIES_SCREAM_TAIL, SPECIES_BRUTE_BONNET, SPECIES_FLUTTER_MANE, SPECIES_SLITHER_WING,
	SPECIES_SANDY_SHOCKS, SPECIES_IRON_BUNDLE, SPECIES_IRON_HANDS, SPECIES_IRON_JUGULIS,
	SPECIES_IRON_MOTH, SPECIES_IRON_THORNS, SPECIES_ROARING_MOON, SPECIES_IRON_VALIANT,
	SPECIES_KORAIDON, SPECIES_MIRAIDON, SPECIES_OGERPON, SPECIES_HAWLUCHA,
	SPECIES_FLOETTE, SPECIES_ZERAORA, SPECIES_GOLURK, SPECIES_GOLISOPOD,
	SPECIES_SCOVILLAIN, SPECIES_BAXCALIBUR, SPECIES_TATSUGIRI, SPECIES_GLIMMORA,
};
